// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/chatpb/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	ChatType_CHAT_TYPE_UNSPECIFIED ChatType = 0
	ChatType_PRIVATE               ChatType = 1
	ChatType_GROUP                 ChatType = 2
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "CHAT_TYPE_UNSPECIFIED",
		1: "PRIVATE",
		2: "GROUP",
	}
	ChatType_value = map[string]int32{
		"CHAT_TYPE_UNSPECIFIED": 0,
		"PRIVATE":               1,
		"GROUP":                 2,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chatpb_chat_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_proto_chatpb_chat_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{0}
}

type BindingType int32

const (
	BindingType_BINDING_TYPE_UNSPECIFIED BindingType = 0
	BindingType_ADVICE                   BindingType = 1
	BindingType_AUTOREPLY                BindingType = 2
)

// Enum value maps for BindingType.
var (
	BindingType_name = map[int32]string{
		0: "BINDING_TYPE_UNSPECIFIED",
		1: "ADVICE",
		2: "AUTOREPLY",
	}
	BindingType_value = map[string]int32{
		"BINDING_TYPE_UNSPECIFIED": 0,
		"ADVICE":                   1,
		"AUTOREPLY":                2,
	}
)

func (x BindingType) Enum() *BindingType {
	p := new(BindingType)
	*p = x
	return p
}

func (x BindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chatpb_chat_proto_enumTypes[1].Descriptor()
}

func (BindingType) Type() protoreflect.EnumType {
	return &file_proto_chatpb_chat_proto_enumTypes[1]
}

func (x BindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingType.Descriptor instead.
func (BindingType) EnumDescriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{1}
}

type GetChatByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByIDRequest) Reset() {
	*x = GetChatByIDRequest{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIDRequest) ProtoMessage() {}

func (x *GetChatByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIDRequest.ProtoReflect.Descriptor instead.
func (*GetChatByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetChatByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ChatType      ChatType               `protobuf:"varint,3,opt,name=chat_type,json=chatType,proto3,enum=chatpb.ChatType" json:"chat_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatByIDResponse) Reset() {
	*x = GetChatByIDResponse{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatByIDResponse) ProtoMessage() {}

func (x *GetChatByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatByIDResponse.ProtoReflect.Descriptor instead.
func (*GetChatByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatByIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetChatByIDResponse) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *GetChatByIDResponse) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_CHAT_TYPE_UNSPECIFIED
}

func (x *GetChatByIDResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetBindingsByChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindingsByChatRequest) Reset() {
	*x = GetBindingsByChatRequest{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindingsByChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindingsByChatRequest) ProtoMessage() {}

func (x *GetBindingsByChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindingsByChatRequest.ProtoReflect.Descriptor instead.
func (*GetBindingsByChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetBindingsByChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ChatBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BindingType   BindingType            `protobuf:"varint,2,opt,name=binding_type,json=bindingType,proto3,enum=chatpb.BindingType" json:"binding_type,omitempty"`
	ThreadId      string                 `protobuf:"bytes,3,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatBinding) Reset() {
	*x = ChatBinding{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBinding) ProtoMessage() {}

func (x *ChatBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBinding.ProtoReflect.Descriptor instead.
func (*ChatBinding) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatBinding) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatBinding) GetBindingType() BindingType {
	if x != nil {
		return x.BindingType
	}
	return BindingType_BINDING_TYPE_UNSPECIFIED
}

func (x *ChatBinding) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ChatBinding) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetUsersByChatIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByChatIDRequest) Reset() {
	*x = GetUsersByChatIDRequest{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByChatIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByChatIDRequest) ProtoMessage() {}

func (x *GetUsersByChatIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByChatIDRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByChatIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersByChatIDRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetUsersByChatIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByChatIDResponse) Reset() {
	*x = GetUsersByChatIDResponse{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByChatIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByChatIDResponse) ProtoMessage() {}

func (x *GetUsersByChatIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByChatIDResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByChatIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersByChatIDResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetBindingsByChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*ChatBinding         `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindingsByChatResponse) Reset() {
	*x = GetBindingsByChatResponse{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindingsByChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindingsByChatResponse) ProtoMessage() {}

func (x *GetBindingsByChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindingsByChatResponse.ProtoReflect.Descriptor instead.
func (*GetBindingsByChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetBindingsByChatResponse) GetBindings() []*ChatBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type GetUserWithChatByThreadIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithChatByThreadIDRequest) Reset() {
	*x = GetUserWithChatByThreadIDRequest{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithChatByThreadIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithChatByThreadIDRequest) ProtoMessage() {}

func (x *GetUserWithChatByThreadIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithChatByThreadIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserWithChatByThreadIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserWithChatByThreadIDRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetUserWithChatByThreadIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithChatByThreadIDResponse) Reset() {
	*x = GetUserWithChatByThreadIDResponse{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithChatByThreadIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithChatByThreadIDResponse) ProtoMessage() {}

func (x *GetUserWithChatByThreadIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithChatByThreadIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserWithChatByThreadIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserWithChatByThreadIDResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserWithChatByThreadIDResponse) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetUserWithChatByThreadIDResponse) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetThreadContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadContextRequest) Reset() {
	*x = GetThreadContextRequest{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadContextRequest) ProtoMessage() {}

func (x *GetThreadContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadContextRequest.ProtoReflect.Descriptor instead.
func (*GetThreadContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetThreadContextRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type GetThreadContextResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderUserId    int64                  `protobuf:"varint,1,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	SenderUserEmail string                 `protobuf:"bytes,2,opt,name=sender_user_email,json=senderUserEmail,proto3" json:"sender_user_email,omitempty"`
	ChatId          int64                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatUserIds     []int64                `protobuf:"varint,4,rep,packed,name=chat_user_ids,json=chatUserIds,proto3" json:"chat_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetThreadContextResponse) Reset() {
	*x = GetThreadContextResponse{}
	mi := &file_proto_chatpb_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadContextResponse) ProtoMessage() {}

func (x *GetThreadContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chatpb_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadContextResponse.ProtoReflect.Descriptor instead.
func (*GetThreadContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_chatpb_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetThreadContextResponse) GetSenderUserId() int64 {
	if x != nil {
		return x.SenderUserId
	}
	return 0
}

func (x *GetThreadContextResponse) GetSenderUserEmail() string {
	if x != nil {
		return x.SenderUserEmail
	}
	return ""
}

func (x *GetThreadContextResponse) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetThreadContextResponse) GetChatUserIds() []int64 {
	if x != nil {
		return x.ChatUserIds
	}
	return nil
}

var File_proto_chatpb_chat_proto protoreflect.FileDescriptor

const file_proto_chatpb_chat_proto_rawDesc = "" +
	"\n" +
	"\x17proto/chatpb/chat.proto\x12\x06chatpb\"$\n" +
	"\x12GetChatByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x92\x01\n" +
	"\x13GetChatByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12-\n" +
	"\tchat_type\x18\x03 \x01(\x0e2\x10.chatpb.ChatTypeR\bchatType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"3\n" +
	"\x18GetBindingsByChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x94\x01\n" +
	"\vChatBinding\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x126\n" +
	"\fbinding_type\x18\x02 \x01(\x0e2\x13.chatpb.BindingTypeR\vbindingType\x12\x1b\n" +
	"\tthread_id\x18\x03 \x01(\tR\bthreadId\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\x03R\x06chatId\"2\n" +
	"\x17GetUsersByChatIDRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"5\n" +
	"\x18GetUsersByChatIDResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"L\n" +
	"\x19GetBindingsByChatResponse\x12/\n" +
	"\bbindings\x18\x01 \x03(\v2\x13.chatpb.ChatBindingR\bbindings\"?\n" +
	" GetUserWithChatByThreadIDRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"t\n" +
	"!GetUserWithChatByThreadIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\"6\n" +
	"\x17GetThreadContextRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\"\xa9\x01\n" +
	"\x18GetThreadContextResponse\x12$\n" +
	"\x0esender_user_id\x18\x01 \x01(\x03R\fsenderUserId\x12*\n" +
	"\x11sender_user_email\x18\x02 \x01(\tR\x0fsenderUserEmail\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x03R\x06chatId\x12\"\n" +
	"\rchat_user_ids\x18\x04 \x03(\x03R\vchatUserIds*=\n" +
	"\bChatType\x12\x19\n" +
	"\x15CHAT_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\t\n" +
	"\x05GROUP\x10\x02*F\n" +
	"\vBindingType\x12\x1c\n" +
	"\x18BINDING_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ADVICE\x10\x01\x12\r\n" +
	"\tAUTOREPLY\x10\x022\xcf\x03\n" +
	"\vChatService\x12F\n" +
	"\vGetChatByID\x12\x1a.chatpb.GetChatByIDRequest\x1a\x1b.chatpb.GetChatByIDResponse\x12X\n" +
	"\x11GetBindingsByChat\x12 .chatpb.GetBindingsByChatRequest\x1a!.chatpb.GetBindingsByChatResponse\x12p\n" +
	"\x19GetUserWithChatByThreadID\x12(.chatpb.GetUserWithChatByThreadIDRequest\x1a).chatpb.GetUserWithChatByThreadIDResponse\x12U\n" +
	"\x10GetUsersByChatID\x12\x1f.chatpb.GetUsersByChatIDRequest\x1a .chatpb.GetUsersByChatIDResponse\x12U\n" +
	"\x10GetThreadContext\x12\x1f.chatpb.GetThreadContextRequest\x1a .chatpb.GetThreadContextResponseB=Z;github.com/Vovarama1992/go-ai-messenger/proto/chatpb;chatpbb\x06proto3"

var (
	file_proto_chatpb_chat_proto_rawDescOnce sync.Once
	file_proto_chatpb_chat_proto_rawDescData []byte
)

func file_proto_chatpb_chat_proto_rawDescGZIP() []byte {
	file_proto_chatpb_chat_proto_rawDescOnce.Do(func() {
		file_proto_chatpb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chatpb_chat_proto_rawDesc), len(file_proto_chatpb_chat_proto_rawDesc)))
	})
	return file_proto_chatpb_chat_proto_rawDescData
}

var file_proto_chatpb_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_chatpb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_chatpb_chat_proto_goTypes = []any{
	(ChatType)(0),                             // 0: chatpb.ChatType
	(BindingType)(0),                          // 1: chatpb.BindingType
	(*GetChatByIDRequest)(nil),                // 2: chatpb.GetChatByIDRequest
	(*GetChatByIDResponse)(nil),               // 3: chatpb.GetChatByIDResponse
	(*GetBindingsByChatRequest)(nil),          // 4: chatpb.GetBindingsByChatRequest
	(*ChatBinding)(nil),                       // 5: chatpb.ChatBinding
	(*GetUsersByChatIDRequest)(nil),           // 6: chatpb.GetUsersByChatIDRequest
	(*GetUsersByChatIDResponse)(nil),          // 7: chatpb.GetUsersByChatIDResponse
	(*GetBindingsByChatResponse)(nil),         // 8: chatpb.GetBindingsByChatResponse
	(*GetUserWithChatByThreadIDRequest)(nil),  // 9: chatpb.GetUserWithChatByThreadIDRequest
	(*GetUserWithChatByThreadIDResponse)(nil), // 10: chatpb.GetUserWithChatByThreadIDResponse
	(*GetThreadContextRequest)(nil),           // 11: chatpb.GetThreadContextRequest
	(*GetThreadContextResponse)(nil),          // 12: chatpb.GetThreadContextResponse
}
var file_proto_chatpb_chat_proto_depIdxs = []int32{
	0,  // 0: chatpb.GetChatByIDResponse.chat_type:type_name -> chatpb.ChatType
	1,  // 1: chatpb.ChatBinding.binding_type:type_name -> chatpb.BindingType
	5,  // 2: chatpb.GetBindingsByChatResponse.bindings:type_name -> chatpb.ChatBinding
	2,  // 3: chatpb.ChatService.GetChatByID:input_type -> chatpb.GetChatByIDRequest
	4,  // 4: chatpb.ChatService.GetBindingsByChat:input_type -> chatpb.GetBindingsByChatRequest
	9,  // 5: chatpb.ChatService.GetUserWithChatByThreadID:input_type -> chatpb.GetUserWithChatByThreadIDRequest
	6,  // 6: chatpb.ChatService.GetUsersByChatID:input_type -> chatpb.GetUsersByChatIDRequest
	11, // 7: chatpb.ChatService.GetThreadContext:input_type -> chatpb.GetThreadContextRequest
	3,  // 8: chatpb.ChatService.GetChatByID:output_type -> chatpb.GetChatByIDResponse
	8,  // 9: chatpb.ChatService.GetBindingsByChat:output_type -> chatpb.GetBindingsByChatResponse
	10, // 10: chatpb.ChatService.GetUserWithChatByThreadID:output_type -> chatpb.GetUserWithChatByThreadIDResponse
	7,  // 11: chatpb.ChatService.GetUsersByChatID:output_type -> chatpb.GetUsersByChatIDResponse
	12, // 12: chatpb.ChatService.GetThreadContext:output_type -> chatpb.GetThreadContextResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_chatpb_chat_proto_init() }
func file_proto_chatpb_chat_proto_init() {
	if File_proto_chatpb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chatpb_chat_proto_rawDesc), len(file_proto_chatpb_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chatpb_chat_proto_goTypes,
		DependencyIndexes: file_proto_chatpb_chat_proto_depIdxs,
		EnumInfos:         file_proto_chatpb_chat_proto_enumTypes,
		MessageInfos:      file_proto_chatpb_chat_proto_msgTypes,
	}.Build()
	File_proto_chatpb_chat_proto = out.File
	file_proto_chatpb_chat_proto_goTypes = nil
	file_proto_chatpb_chat_proto_depIdxs = nil
}
