// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/messagepb/message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_messagepb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagepb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_messagepb_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SentAt        int64                  `protobuf:"varint,3,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	SenderEmail   string                 `protobuf:"bytes,4,opt,name=senderEmail,proto3" json:"senderEmail,omitempty"` // ← вот это добавляем
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_messagepb_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagepb_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_messagepb_message_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *ChatMessage) GetSenderEmail() string {
	if x != nil {
		return x.SenderEmail
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_messagepb_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagepb_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_messagepb_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_messagepb_message_proto protoreflect.FileDescriptor

const file_proto_messagepb_message_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/messagepb/message.proto\x12\tmessagepb\"-\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"}\n" +
	"\vChatMessage\x12\x1a\n" +
	"\bsenderId\x18\x01 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06sentAt\x18\x03 \x01(\x03R\x06sentAt\x12 \n" +
	"\vsenderEmail\x18\x04 \x01(\tR\vsenderEmail\"I\n" +
	"\x13GetMessagesResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.messagepb.ChatMessageR\bmessages2d\n" +
	"\x0eMessageService\x12R\n" +
	"\x11GetMessagesByChat\x12\x1d.messagepb.GetMessagesRequest\x1a\x1e.messagepb.GetMessagesResponseBCZAgithub.com/Vovarama1992/go-ai-messenger/proto/messagepb;messagepbb\x06proto3"

var (
	file_proto_messagepb_message_proto_rawDescOnce sync.Once
	file_proto_messagepb_message_proto_rawDescData []byte
)

func file_proto_messagepb_message_proto_rawDescGZIP() []byte {
	file_proto_messagepb_message_proto_rawDescOnce.Do(func() {
		file_proto_messagepb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messagepb_message_proto_rawDesc), len(file_proto_messagepb_message_proto_rawDesc)))
	})
	return file_proto_messagepb_message_proto_rawDescData
}

var file_proto_messagepb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_messagepb_message_proto_goTypes = []any{
	(*GetMessagesRequest)(nil),  // 0: messagepb.GetMessagesRequest
	(*ChatMessage)(nil),         // 1: messagepb.ChatMessage
	(*GetMessagesResponse)(nil), // 2: messagepb.GetMessagesResponse
}
var file_proto_messagepb_message_proto_depIdxs = []int32{
	1, // 0: messagepb.GetMessagesResponse.messages:type_name -> messagepb.ChatMessage
	0, // 1: messagepb.MessageService.GetMessagesByChat:input_type -> messagepb.GetMessagesRequest
	2, // 2: messagepb.MessageService.GetMessagesByChat:output_type -> messagepb.GetMessagesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_messagepb_message_proto_init() }
func file_proto_messagepb_message_proto_init() {
	if File_proto_messagepb_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messagepb_message_proto_rawDesc), len(file_proto_messagepb_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messagepb_message_proto_goTypes,
		DependencyIndexes: file_proto_messagepb_message_proto_depIdxs,
		MessageInfos:      file_proto_messagepb_message_proto_msgTypes,
	}.Build()
	File_proto_messagepb_message_proto = out.File
	file_proto_messagepb_message_proto_goTypes = nil
	file_proto_messagepb_message_proto_depIdxs = nil
}
